# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

environment:
  RUST_BACKTRACE: full
  CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"
  # The appveyor image we use has a pretty huge set of things installed... we make the
  # initial PATH something sane so we know what to expect
  PATH: "C:\\windows\\system32;\
    C:\\windows;\
    C:\\windows\\System32\\Wbem;\
    C:\\windows\\System32\\WindowsPowerShell\\v1.0;\
    C:\\ProgramData\\chocolatey\\bin;\
    C:\\Python27;\
    C:\\Python27\\Scripts;\
    C:\\Tools\\PsTools;\
    C:\\Tools\\NuGet3;\
    C:\\Program Files\\Microsoft\\Web Platform Installer\\;\
    C:\\Program Files\\7-Zip;\
    C:\\Program Files\\Mercurial;\
    C:\\Program Files (x86)\\Subversion\\bin;\
    C:\\Program Files (x86)\\CMake\\bin;\
    C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;\
    C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;\
    C:\\Program Files\\Amazon\\AWSCLI\\;\
    C:\\Program Files\\Microsoft Windows Performance Toolkit\\;\
    C:\\Program Files\\LLVM\\bin;\
    C:\\Program Files\\Git LFS;\
    C:\\Program Files\\Git\\cmd;\
    C:\\Program Files\\Git\\usr\\bin;\
    C:\\Program Files\\AppVeyor\\BuildAgent;"
  global:
    RUST_VERSION: nightly
    CRATE_NAME: traeger

  matrix:
    - TARGET: nightly-x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "http://servo-rust.s3.amazonaws.com/build/MozillaBuildSetup-2.2.0.exe"
  - ps: .\MozillaBuildSetup-2.2.0.exe /S | Out-Null
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - if %TARGET:*-msvc=msvc%==msvc set BUILD_ENV=msvc
  - if %BUILD_ENV%==msvc call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
  - if %BUILD_ENV%==msvc copy C:\mozilla-build\yasm\yasm.exe C:\mozilla-build\msys\bin
  - if %BUILD_ENV%==msvc copy C:\mozilla-build\mozmake\mozmake.exe C:\mozilla-build\msys\bin
  - if %BUILD_ENV%==msvc set MOZTOOLS_PATH=C:\mozilla-build\msys\bin
  - if %BUILD_ENV%==msvc set NATIVE_WIN32_PYTHON=C:/Python27/python.exe
  - rustc -vV
  - cargo -vV

cache:
  - .servo -> rust-commit-hash, cargo-commit-hash
  - .cargo -> rust-commit-hash, cargo-commit-hash
  - .ccache

build_script:
  cargo build --verbose

test: off

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master

before_deploy:
  - cargo build --release --target %TARGET%
  - COPY target\%TARGET%\release\traeger.exe traeger-%APPVEYOR_REPO_TAG_NAME%-%TARGET%

deploy:
  artifact: traeger-%TRAVIS_TAG%-%TARGET%
  auth_token:
    secure: URnWKwvB3B4OyvTmuf0yIHAuxfQQBmL6bEm47A8LAwv9528u6t8MguJwKVmopHY8
  on:
    appveyor_repo_tag: true
  provider: GitHub

notifications:
  - provider: Email
    on_build_success: false
