[package]
name = "traeger"
version = "0.1.0"
authors = ["Krzysztof Jan Modras <chrmod@chrmod.net>"]

[dependencies]
webextension-protocol = { git = "https://github.com/chrmod/rust-webextension-protocol" }
#webextension-protocol = { path = "/home/chrmod/Projects/chrmod/webextension-rust-template" }
js = {git = "https://github.com/servo/rust-mozjs", features = ["promises"]}
